package Pinturas;
// Generated 12-feb-2020 11:22:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentarios generated by hbm2java
 */
@Entity
@Table(name = "Comentarios",
         catalog = "Pinturas"
)
public class Comentarios implements java.io.Serializable {

    @Id
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    private String idcomentarios;
    private Cuadro cuadro;
    private Usuarios usuarios;
    private String comentario;
    private Date fecha;

    public Comentarios() {
    }

    public Comentarios(String idcomentarios, Cuadro cuadro, Usuarios usuarios) {
        this.idcomentarios = idcomentarios;
        this.cuadro = cuadro;
        this.usuarios = usuarios;
    }

    public Comentarios(String idcomentarios, Cuadro cuadro, Usuarios usuarios, String comentario, Date fecha) {
        this.idcomentarios = idcomentarios;
        this.cuadro = cuadro;
        this.usuarios = usuarios;
        this.comentario = comentario;
        this.fecha = fecha;
    }

    @Id

    @Column(name = "idcomentarios", unique = true, nullable = false, length = 20)
    public String getIdcomentarios() {
        return this.idcomentarios;
    }

    public void setIdcomentarios(String idcomentarios) {
        this.idcomentarios = idcomentarios;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Cuadro_idCuadro", nullable = false)
    public Cuadro getCuadro() {
        return this.cuadro;
    }

    public void setCuadro(Cuadro cuadro) {
        this.cuadro = cuadro;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Usuarios_idUsuario", nullable = false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Column(name = "comentario", length = 45)
    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
