package Pinturas;
// Generated 12-feb-2020 11:22:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuadro generated by hbm2java
 */
@Entity
@Table(name = "Cuadro",
         catalog = "Pinturas"
)
public class Cuadro implements java.io.Serializable {

    @Id
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    private String idCuadro;
    private Pintor pintor;
    private String titulo;
    private Integer anio;
    private Set comentarioses = new HashSet(0);

    public Cuadro() {
    }

    public Cuadro(String idCuadro, Pintor pintor) {
        this.idCuadro = idCuadro;
        this.pintor = pintor;
    }

    public Cuadro(String idCuadro, Pintor pintor, String titulo, Integer anio, Set comentarioses) {
        this.idCuadro = idCuadro;
        this.pintor = pintor;
        this.titulo = titulo;
        this.anio = anio;
        this.comentarioses = comentarioses;
    }

    @Id

    @Column(name = "idCuadro", unique = true, nullable = false, length = 20)
    public String getIdCuadro() {
        return this.idCuadro;
    }

    public void setIdCuadro(String idCuadro) {
        this.idCuadro = idCuadro;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Pintor_idPintor", nullable = false)
    public Pintor getPintor() {
        return this.pintor;
    }

    public void setPintor(Pintor pintor) {
        this.pintor = pintor;
    }

    @Column(name = "titulo", length = 45)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "anio")
    public Integer getAnio() {
        return this.anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cuadro")
    public Set getComentarioses() {
        return this.comentarioses;
    }

    public void setComentarioses(Set comentarioses) {
        this.comentarioses = comentarioses;
    }

}
