package Pinturas;
// Generated 12-feb-2020 11:22:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pintor generated by hbm2java
 */
@Entity
@Table(name = "Pintor",
         catalog = "Pinturas"
)
public class Pintor implements java.io.Serializable {

    @Id
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    private String idPintor;
    private String nombre;
    private Integer anioNacimiento;
    private String estilo;
    private Set cuadros = new HashSet(0);

    public Pintor() {
    }

    public Pintor(String idPintor) {
        this.idPintor = idPintor;
    }

    public Pintor(String idPintor, String nombre, Integer anioNacimiento, String estilo, Set cuadros) {
        this.idPintor = idPintor;
        this.nombre = nombre;
        this.anioNacimiento = anioNacimiento;
        this.estilo = estilo;
        this.cuadros = cuadros;
    }

    @Id

    @Column(name = "idPintor", unique = true, nullable = false, length = 20)
    public String getIdPintor() {
        return this.idPintor;
    }

    public void setIdPintor(String idPintor) {
        this.idPintor = idPintor;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "anioNacimiento")
    public Integer getAnioNacimiento() {
        return this.anioNacimiento;
    }

    public void setAnioNacimiento(Integer anioNacimiento) {
        this.anioNacimiento = anioNacimiento;
    }

    @Column(name = "estilo", length = 45)
    public String getEstilo() {
        return this.estilo;
    }

    public void setEstilo(String estilo) {
        this.estilo = estilo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pintor")
    public Set getCuadros() {
        return this.cuadros;
    }

    public void setCuadros(Set cuadros) {
        this.cuadros = cuadros;
    }

}
