package Pinturas;
// Generated 12-feb-2020 11:22:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "Usuarios",
         catalog = "Pinturas"
)
public class Usuarios implements java.io.Serializable {

    @Id
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    private String idUsuario;
    private String nombre;
    private Set comentarioses = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Usuarios(String idUsuario, String nombre, Set comentarioses) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.comentarioses = comentarioses;
    }

    @Id

    @Column(name = "idUsuario", unique = true, nullable = false, length = 20)
    public String getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "nombre", length = 30)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
    public Set getComentarioses() {
        return this.comentarioses;
    }

    public void setComentarioses(Set comentarioses) {
        this.comentarioses = comentarioses;
    }

}
