package Modelo;
// Generated 19-feb-2020 11:18:55 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Direccion generated by hbm2java
 */
@Entity
public class Direccion implements java.io.Serializable {

    @Id
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idDireccion;
    private String calle;
    private Integer codigoPostal;

    public Direccion() {
    }

    public Direccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }

    public Direccion(int idDireccion, String calle, Integer codigoPostal) {
        this.idDireccion = idDireccion;
        this.calle = calle;
        this.codigoPostal = codigoPostal;
    }

    public int getIdDireccion() {
        return this.idDireccion;
    }

    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }

    public String getCalle() {
        return this.calle;
    }

    public void setCalle(String calle) {
        this.calle = calle;
    }

    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }

    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

}
