package Modelo;
// Generated 19-feb-2020 11:18:55 by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Persona generated by hbm2java
 */
@Entity
public class Persona implements java.io.Serializable {

    @Id
    private int idPersona;
    private String nombre;
    @OneToOne(cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
    private Direccion direccion;

    public Persona() {
    }

    public Persona(int idPersona, Direccion direccion) {
        this.idPersona = idPersona;
        this.direccion = direccion;
    }

    public Persona(int idPersona, Direccion direccion, String nombre) {
        this.idPersona = idPersona;
        this.direccion = direccion;
        this.nombre = nombre;
    }

    public int getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    public Direccion getDireccion() {
        return this.direccion;
    }

    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
