package Modelo;
// Generated 22-feb-2020 18:41:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="Persona")
public class Persona implements java.io.Serializable {

    @Id
    private int idPersona;
    private String nombre;
    //Uno A Muchos BIDIRECCIONARL
    //Deberemos añadir mappedBy y le indicamos la clase dueña de la relación, 
    //en estos casos es la del lado "muchos"
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "persona")
    private List<Libro> libros = new ArrayList<Libro>();

    public Persona() {
    }

    public Persona(int idPersona) {
        this.idPersona = idPersona;
    }

    public Persona(int idPersona, String nombre, List libros) {
        this.idPersona = idPersona;
        this.nombre = nombre;
        this.libros = libros;
    }

    public int getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List getLibros() {
        return this.libros;
    }

    public void setLibros(List libros) {
        this.libros = libros;
    }

    public void addLibro(Libro libro) {
        this.libros.add(libro);
    }
}
